spring.application.name=atk-nomina-batch
app.diagnostics.enabled=false
app.admin.enabled=false
app.endpoints.operations.enabled=false
app.config.validation.strict=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

atk.batch.simulation-nominas=1000
atk.batch.default-max-nominas=50
atk.batch.max-nominas-per-run=50
atk.batch.simulation-iterations=100
atk.batch.chunk-size=20
atk.batch.real.chunk-size=1
atk.batch.sample-file=classpath:samples/ZSVIDA_Nom15960.xml

artikos.http.connect-timeout-ms=5000
artikos.http.read-timeout-ms=30000
artikos.retry.enabled=true
artikos.retry.max-attempts=3
artikos.retry.backoff-ms=1000
artikos.source.mode=remote
artikos.source.local-xml-path=
artikos.confirm.enabled=true
artikos.result.enabled=true

artikos.qa.endpoints.nomina-url=https://integracion-qa.artikos.cl/Ws_B2BOut/AtkWS_DocExtractorB2B.asmx
artikos.qa.endpoints.connector-url=https://integracion-qa.artikos.cl/Ws_B2B/AtkWS_DocConnectorB2B.asmx
artikos.qa.soap-action=
artikos.qa.nomina-soap-action="AtkWs_DocExtractor/EjecutaTrx"
artikos.qa.connector-soap-action="AtkWs_DocConnectorB2B/EjecutaTrx"

procurement.mapping.document-type=CMP
procurement.mapping.cmp-document-type=FEC
procurement.mapping.cod-sistem=CM
procurement.mapping.company-by-profile.GENERALES=002
procurement.mapping.company-by-profile.VIDA=001
procurement.mapping.num-periodo=202606
procurement.mapping.cod-contbl=DEFAULT
procurement.mapping.cod-tip-cuenta=2
procurement.mapping.cod-tip-unid=UN
procurement.mapping.grl-cod-item=SERVICIO
procurement.mapping.line-gloss=BENEFICIOS AL PERSONAL
procurement.mapping.default-currency=$
procurement.mapping.val-tip-cambio=1
procurement.mapping.pct-dscnto=0
procurement.mapping.mto-dscnto=0
procurement.mapping.pct-iva=19
procurement.mapping.codigo-rec-iva=REC
procurement.mapping.default-cantidad=1

procurement.client.enabled=false
procurement.client.base-url=
procurement.client.document-path=/api/v1/document
procurement.client.connect-timeout-ms=5000
procurement.client.read-timeout-ms=30000
procurement.integration.enabled=false
