spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

atk.oracle.url=jdbc:oracle:thin:@172.18.10.208:1521:mettti
atk.oracle.username=ASI
atk.oracle.password=CHANGE_ME
atk.oracle.driver-class-name=oracle.jdbc.OracleDriver
atk.oracle.tns-admin=

atk.batch.simulation-nominas=1000
atk.batch.chunk-size=25
atk.batch.sample-file=classpath:samples/ZSVIDA_Nom15960.xml

artikos.qa.nomina-url=https://integracion-qa.artikos.cl/Ws_B2BOut/AtkWS_DocExtractorB2B.asmx
artikos.qa.connector-url=https://integracion-qa.artikos.cl/Ws_B2B/AtkWS_DocConnectorB2B.asmx
artikos.qa.soap-action=
artikos.qa.nomina-soap-action="AtkWs_DocExtractor/EjecutaTrx"
artikos.qa.connector-soap-action="AtkWs_DocConnectorB2B/EjecutaTrx"
artikos.qa.profiles.VIDA.token=REEMPLAZAR_TOKEN_VIDA
artikos.qa.profiles.VIDA.msg-from-address=ZSVIDA
artikos.qa.profiles.VIDA.msg-cod-from-address=REEMPLAZAR
artikos.qa.profiles.VIDA.msg-to-address=ARTIKOS
artikos.qa.profiles.VIDA.msg-cod-sis=SAF
artikos.qa.profiles.VIDA.msg-cod-externo=REEMPLAZAR
artikos.qa.profiles.GENERALES.token=REEMPLAZAR_TOKEN_GENERALES
artikos.qa.profiles.GENERALES.msg-from-address=ZSGRALES
artikos.qa.profiles.GENERALES.msg-cod-from-address=REEMPLAZAR
artikos.qa.profiles.GENERALES.msg-to-address=ARTIKOS
artikos.qa.profiles.GENERALES.msg-cod-sis=SAF
artikos.qa.profiles.GENERALES.msg-cod-externo=REEMPLAZAR
