spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

atk.oracle.url=jdbc:oracle:thin:@172.18.10.208:1521:mettti
atk.oracle.username=ASI
atk.oracle.password=CHANGE_ME
atk.oracle.driver-class-name=oracle.jdbc.OracleDriver
atk.oracle.tns-admin=

atk.batch.simulation-nominas=1000
atk.batch.chunk-size=25
atk.batch.sample-file=classpath:samples/ZSVIDA_Nom15960.xml
