spring.profiles.active=local
spring.application.name=atk-nomina-batch-poc

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

atk.batch.simulation-nominas=1000
atk.batch.simulation-iterations=100
atk.batch.chunk-size=20
atk.batch.real.chunk-size=1
atk.batch.sample-file=classpath:samples/ZSVIDA_Nom15960.xml

artikos.qa.endpoints.nomina-url=https://integracion-qa.artikos.cl/Ws_B2BOut/AtkWS_DocExtractorB2B.asmx
artikos.qa.endpoints.connector-url=https://integracion-qa.artikos.cl/Ws_B2B/AtkWS_DocConnectorB2B.asmx
artikos.qa.soap-action=
artikos.qa.nomina-soap-action="AtkWs_DocExtractor/EjecutaTrx"
artikos.qa.connector-soap-action="AtkWs_DocConnectorB2B/EjecutaTrx"
