CREATE TABLE CONTROL_NOMINA (
    JOB_EXECUTION_ID NUMBER NOT NULL,
    NUMERO_NOMINA NUMBER NOT NULL,
    TOTAL_DOCUMENTS NUMBER,
    TOTAL_OK NUMBER,
    TOTAL_NOK NUMBER,
    TOTAL_CONCILIACIONES NUMBER,
    TOTAL_DISTRIBUCIONES NUMBER,
    STATUS VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR2(500),
    CONSTRAINT PK_CONTROL_NOMINA PRIMARY KEY (JOB_EXECUTION_ID, NUMERO_NOMINA),
    CONSTRAINT CK_CONTROL_NOMINA_STATUS CHECK (STATUS IN ('PROCESSING', 'OK', 'NOK', 'ERROR'))
);

CREATE INDEX IDX_CONTROL_NOMINA_JOB
    ON CONTROL_NOMINA (JOB_EXECUTION_ID);

CREATE INDEX IDX_CONTROL_NOMINA_STATUS
    ON CONTROL_NOMINA (STATUS);

CREATE INDEX IDX_CONTROL_NOMINA_NUMERO
    ON CONTROL_NOMINA (NUMERO_NOMINA);

COMMENT ON TABLE CONTROL_NOMINA IS 'Control de estado de procesamiento por nomina Artikos.';

COMMENT ON COLUMN CONTROL_NOMINA.JOB_EXECUTION_ID IS 'Identificador de ejecucion Spring Batch asociado.';
COMMENT ON COLUMN CONTROL_NOMINA.NUMERO_NOMINA IS 'Numero de nomina Artikos procesada.';
COMMENT ON COLUMN CONTROL_NOMINA.TOTAL_DOCUMENTS IS 'Cantidad total de documentos informados en la nomina.';
COMMENT ON COLUMN CONTROL_NOMINA.TOTAL_OK IS 'Cantidad de documentos procesados correctamente.';
COMMENT ON COLUMN CONTROL_NOMINA.TOTAL_NOK IS 'Cantidad de documentos procesados con observaciones o rechazo.';
COMMENT ON COLUMN CONTROL_NOMINA.TOTAL_CONCILIACIONES IS 'Cantidad total de conciliaciones detectadas.';
COMMENT ON COLUMN CONTROL_NOMINA.TOTAL_DISTRIBUCIONES IS 'Cantidad total de distribuciones detectadas.';
COMMENT ON COLUMN CONTROL_NOMINA.STATUS IS 'Estado de procesamiento de la nomina: PROCESSING, OK, NOK o ERROR.';
COMMENT ON COLUMN CONTROL_NOMINA.CREATED_AT IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN CONTROL_NOMINA.UPDATED_AT IS 'Fecha y hora de ultima actualizacion del registro.';
COMMENT ON COLUMN CONTROL_NOMINA.ERROR_MESSAGE IS 'Mensaje de error asociado al procesamiento, si aplica.';
