CREATE TABLE IF NOT EXISTS CONTROL_NOMINA (
    JOB_EXECUTION_ID NUMBER NOT NULL,
    NUMERO_NOMINA NUMBER NOT NULL,
    TOTAL_DOCUMENTS NUMBER,
    TOTAL_OK NUMBER,
    TOTAL_NOK NUMBER,
    TOTAL_CONCILIACIONES NUMBER,
    TOTAL_DISTRIBUCIONES NUMBER,
    STATUS VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR2(500),
    CONSTRAINT PK_CONTROL_NOMINA PRIMARY KEY (JOB_EXECUTION_ID, NUMERO_NOMINA),
    CONSTRAINT CK_CONTROL_NOMINA_STATUS CHECK (STATUS IN ('PROCESSING', 'OK', 'NOK', 'ERROR'))
);
