CREATE TABLE IF NOT EXISTS CONTROL_NOMINA (
    JOB_EXECUTION_ID NUMBER NOT NULL,
    NUMERO_NOMINA NUMBER NOT NULL,
    TOTAL_DOCUMENTS NUMBER,
    TOTAL_OK NUMBER,
    TOTAL_NOK NUMBER,
    TOTAL_CONCILIACIONES NUMBER,
    TOTAL_DISTRIBUCIONES NUMBER,
    STATUS VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR2(500),
    CONSTRAINT PK_CONTROL_NOMINA PRIMARY KEY (JOB_EXECUTION_ID, NUMERO_NOMINA),
    CONSTRAINT CK_CONTROL_NOMINA_STATUS CHECK (STATUS IN ('PROCESSING', 'OK', 'NOK', 'ERROR'))
);

CREATE TABLE IF NOT EXISTS GRL_MAE_ITEM (
    COD_EMPRES VARCHAR2(3) NOT NULL,
    NUM_PERIODO NUMBER NOT NULL,
    GRL_COD_ITEM VARCHAR2(30) NOT NULL,
    A_IND_VIGE VARCHAR2(1),
    CONSTRAINT PK_GRL_MAE_ITEM PRIMARY KEY (COD_EMPRES, NUM_PERIODO, GRL_COD_ITEM)
);

CREATE TABLE IF NOT EXISTS GRL_MAE_ITEM_DET (
    COD_EMPRES VARCHAR2(3) NOT NULL,
    NUM_PERIODO NUMBER NOT NULL,
    COD_SISTEM VARCHAR2(10) NOT NULL,
    COD_MONEDA VARCHAR2(10) NOT NULL,
    COD_CUENTA NUMBER NOT NULL,
    COD_IMPSTO VARCHAR2(10) NOT NULL,
    GRL_COD_ITEM VARCHAR2(30) NOT NULL,
    COD_TIP_UNID VARCHAR2(10),
    COD_TIP_CNTA_ITEMS VARCHAR2(10),
    COD_CONTBL VARCHAR2(30),
    A_IND_VIGE VARCHAR2(1),
    CONSTRAINT PK_GRL_MAE_ITEM_DET PRIMARY KEY (
        COD_EMPRES, NUM_PERIODO, COD_SISTEM, COD_MONEDA, COD_CUENTA, COD_IMPSTO, GRL_COD_ITEM
    )
);
